import { productSlug, servicePages } from './data/seoContent';
export const defaultSiteUrl='https://www.aureliabeauty.com';
const basePages={
 '/':['Skin-First Skincare, Makeup & Fragrance | Aurelia Beauty','Discover thoughtful skincare, effortless color and intimate scent designed for everyday rituals.'],
 '/products':['Shop Skincare, Makeup & Fragrance | Aurelia Beauty','Explore Aurelia Beauty essentials for hydrated skin, modern color and sensorial body rituals.'],
 '/about':['Our Story | Aurelia Beauty','Meet Aurelia Beauty: skin-first formulas and modern essentials made for real rituals.'],
 '/news-blog/':['The Aurelia Journal | Beauty Rituals & Guides','Beauty notes on skin rituals, ingredients, color and scent from Aurelia Beauty.'],
 '/faq':['Beauty FAQ | Aurelia Beauty','Answers about Aurelia products, formulas, ingredients, samples and partnerships.'],
 '/contact':['Contact & Partnerships | Aurelia Beauty','Talk to Aurelia Beauty about products, wholesale, gifting and private-label partnerships.'],
 '/privacy':['Privacy Policy | Aurelia Beauty','How Aurelia Beauty collects, uses and protects personal information.'],
 '/terms':['Terms of Use | Aurelia Beauty','Terms governing use of the Aurelia Beauty website.'],
 '/privacy-choices':['Privacy Choices | Aurelia Beauty','Manage optional analytics for the Aurelia Beauty website.'],
 '/privacy-request':['Privacy Request | Aurelia Beauty','Submit a request concerning your personal information.']
};
const privatePages={'/login':['Account Sign In | Aurelia Beauty','Sign in to manage partner samples and conversations.'],'/quote':['Partner Sample Edit | Aurelia Beauty','Build a private product edit for your partnership inquiry.'],'/admin':['Product Admin | Aurelia Beauty','Private administration.'],'/admin/users':['User Admin | Aurelia Beauty','Private user administration.'],'/admin/roles':['Role Admin | Aurelia Beauty','Private role administration.'],'/admin/articles':['Journal Admin | Aurelia Beauty','Private editorial workspace.'],'/admin/faqs':['FAQ Admin | Aurelia Beauty','Private FAQ workspace.'],'/admin/privacy':['Privacy Admin | Aurelia Beauty','Private privacy workspace.'],'/support/inbox':['Support Inbox | Aurelia Beauty','Private support workspace.']};
export function buildPublicSeoPaths(products=[],articles=[]){return [...Object.keys(basePages),...Object.keys(servicePages).map(slug=>`/services/${slug}`),...products.map(p=>`/products/${productSlug(p)}`),...articles.filter(a=>a.status==='published').map(a=>`/news-blog/${a.slug}`)]}
export function buildPrerenderPaths(products=[],articles=[]){return [...new Set([...buildPublicSeoPaths(products,articles),...Object.keys(privatePages),'/404'])]}
export function normalizeSeoPath(pathname='/'){if(!pathname)return '/';const clean=pathname.split('?')[0].replace(/\/{2,}/g,'/');if(clean==='/news-blog')return '/news-blog/';return clean.length>1?clean.replace(/\/$/,''):clean}
export function getSeoForPath(pathname='/',products=[],articles=[]){const path=normalizeSeoPath(pathname);const defaults={path,canonical:path,image:'/beauty/hero-aurelia.png',type:'website',noindex:false};if(basePages[path])return {...defaults,title:basePages[path][0],description:basePages[path][1],schemaType:path==='/'||path==='/about'?'organization':'webpage'};if(privatePages[path])return {...defaults,title:privatePages[path][0],description:privatePages[path][1],noindex:true};const pm=path.match(/^\/products\/(.+)$/);if(pm){const product=products.find(p=>productSlug(p)===pm[1]);if(product)return {...defaults,title:`${product.name} | Aurelia Beauty`,description:product.description,image:product.image,schemaType:'product',product}}const sm=path.match(/^\/services\/(.+)$/);if(sm&&servicePages[sm[1]]){const s=servicePages[sm[1]];return {...defaults,title:`${s.title} | Aurelia Beauty`,description:s.intro,image:s.image,schemaType:'webpage'}}const am=path.match(/^\/news-blog\/(.+)$/);if(am){const article=articles.find(a=>a.slug===am[1]);if(article)return {...defaults,title:`${article.title} | Aurelia Beauty`,description:article.summary,image:article.image||defaults.image,type:'article',schemaType:'article',article}}return {...defaults,title:'Page Not Found | Aurelia Beauty',description:'The requested page could not be found.',canonical:null,noindex:true}}
export function getStructuredData(seo,siteUrl=defaultSiteUrl,faqs=[]){const root=siteUrl.replace(/\/$/,'');const url=seo.canonical?`${root}${seo.canonical}`:root;const org={'@type':'Organization',name:'Aurelia Beauty',url:root,description:'Skin-first skincare, modern color and intimate fragrance for everyday rituals.',knowsAbout:['Skincare','Color cosmetics','Fragrance']};if(seo.path==='/faq')return {'@context':'https://schema.org','@type':'FAQPage',mainEntity:faqs.map(f=>({'@type':'Question',name:f.question,acceptedAnswer:{'@type':'Answer',text:f.answer}}))};if(seo.schemaType==='organization')return {'@context':'https://schema.org',...org};if(seo.schemaType==='product'&&seo.product)return {'@context':'https://schema.org','@type':'Product',name:seo.product.name,description:seo.product.description,image:`${root}${seo.product.image}`,sku:seo.product.id,category:seo.product.category,url,offers:{'@type':'Offer',price:seo.product.price,priceCurrency:'USD',availability:'https://schema.org/InStock'}};return {'@context':'https://schema.org','@type':'WebPage',name:seo.title,description:seo.description,url}}
