import { productSlug, servicePages } from './data/seoContent';
export const defaultSiteUrl='https://www.aureliabeauty.com';
const basePages={
 '/':['Cosmetic Ingredients & Formulation Materials | Aurelia','Source performance actives, botanical extracts and functional cosmetic materials with technical documentation and sample support.'],
 '/products':['Cosmetic Raw-Material Portfolio | Aurelia Ingredients','Compare cosmetic ingredient INCI names, functions, use levels, pack sizes, MOQs and sample options.'],
 '/about':['About Aurelia Ingredients','A focused cosmetic raw-material partner for formulators, manufacturers and distributors.'],
 '/news-blog/':['Cosmetic Ingredient Technical Library | Aurelia','Practical notes on cosmetic raw materials, formulation, processing, qualification and documentation.'],
 '/faq':['Cosmetic Ingredient FAQ | Aurelia','Answers about samples, COA, TDS, SDS, MOQ, lead times, formulation guidance and commercial supply.'],
 '/contact':['Request Cosmetic Ingredient Samples & Quotes | Aurelia','Tell Aurelia Ingredients about your formulation, volume, market and documentation needs.'],
 '/privacy':['Privacy Policy | Aurelia Ingredients','How Aurelia Ingredients collects, uses and protects business contact information.'],
 '/terms':['Terms of Use | Aurelia Ingredients','Terms governing use of the Aurelia cosmetic ingredient website.'],
 '/privacy-choices':['Privacy Choices | Aurelia Ingredients','Manage optional analytics for the Aurelia Ingredients website.'],
 '/privacy-request':['Privacy Request | Aurelia Ingredients','Submit a request concerning your personal information.']
};
const privatePages={'/login':['Account Sign In | Aurelia Ingredients','Sign in to manage ingredient samples, RFQs and conversations.'],'/quote':['Ingredient Sample List | Aurelia Ingredients','Build a private cosmetic ingredient sample list and RFQ.'],'/admin':['Ingredient Admin | Aurelia Ingredients','Private cosmetic raw-material administration.'],'/admin/users':['User Admin | Aurelia Ingredients','Private user administration.'],'/admin/roles':['Role Admin | Aurelia Ingredients','Private role administration.'],'/admin/articles':['Technical Library Admin | Aurelia Ingredients','Private ingredient editorial workspace.'],'/admin/faqs':['FAQ Admin | Aurelia Ingredients','Private ingredient FAQ workspace.'],'/admin/privacy':['Privacy Admin | Aurelia Ingredients','Private privacy workspace.'],'/support/inbox':['Ingredient Support Inbox | Aurelia Ingredients','Private technical support workspace.']};
export function buildPublicSeoPaths(products=[],articles=[]){return [...Object.keys(basePages),...Object.keys(servicePages).map(slug=>`/services/${slug}`),...products.map(p=>`/products/${productSlug(p)}`),...articles.filter(a=>a.status==='published').map(a=>`/news-blog/${a.slug}`)]}
export function buildPrerenderPaths(products=[],articles=[]){return [...new Set([...buildPublicSeoPaths(products,articles),...Object.keys(privatePages),'/404'])]}
export function normalizeSeoPath(pathname='/'){if(!pathname)return '/';const clean=pathname.split('?')[0].replace(/\/{2,}/g,'/');if(clean==='/news-blog')return '/news-blog/';return clean.length>1?clean.replace(/\/$/,''):clean}
export function getSeoForPath(pathname='/',products=[],articles=[]){const path=normalizeSeoPath(pathname);const defaults={path,canonical:path,image:'/ingredients/hero-ingredients.png',type:'website',noindex:false};if(basePages[path])return {...defaults,title:basePages[path][0],description:basePages[path][1],schemaType:path==='/'||path==='/about'?'organization':'webpage'};if(privatePages[path])return {...defaults,title:privatePages[path][0],description:privatePages[path][1],noindex:true};const pm=path.match(/^\/products\/(.+)$/);if(pm){const product=products.find(p=>productSlug(p)===pm[1]);if(product)return {...defaults,title:`${product.name} | Aurelia Ingredients`,description:product.description,image:product.image,schemaType:'product',product}}const sm=path.match(/^\/services\/(.+)$/);if(sm&&servicePages[sm[1]]){const s=servicePages[sm[1]];return {...defaults,title:`${s.title} | Aurelia Ingredients`,description:s.intro,image:s.image,schemaType:'webpage'}}const am=path.match(/^\/news-blog\/(.+)$/);if(am){const article=articles.find(a=>a.slug===am[1]);if(article)return {...defaults,title:`${article.title} | Aurelia Ingredients`,description:article.summary,image:article.image||defaults.image,type:'article',schemaType:'article',article}}return {...defaults,title:'Page Not Found | Aurelia Ingredients',description:'The requested page could not be found.',canonical:null,noindex:true}}
export function getStructuredData(seo,siteUrl=defaultSiteUrl,faqs=[]){const root=siteUrl.replace(/\/$/,'');const url=seo.canonical?`${root}${seo.canonical}`:root;const org={'@type':'Organization',name:'Aurelia Ingredients',url:root,description:'A B2B supplier of cosmetic active ingredients, botanical extracts and functional materials.',knowsAbout:['Cosmetic ingredients','INCI','Active ingredients','Botanical extracts','Emollients','Emulsifiers','Cosmetic formulation']};if(seo.path==='/faq')return {'@context':'https://schema.org','@type':'FAQPage',mainEntity:faqs.map(f=>({'@type':'Question',name:f.question,acceptedAnswer:{'@type':'Answer',text:f.answer}}))};if(seo.schemaType==='organization')return {'@context':'https://schema.org',...org};if(seo.schemaType==='product'&&seo.product)return {'@context':'https://schema.org','@type':'Product',name:seo.product.name,description:seo.product.description,image:`${root}${seo.product.image}`,sku:seo.product.id,category:seo.product.category,url,audience:{'@type':'BusinessAudience',audienceType:'Cosmetic formulators, manufacturers, brands and ingredient distributors'},additionalProperty:[{'@type':'PropertyValue',name:'INCI',value:seo.product.inci},{'@type':'PropertyValue',name:'Recommended use',value:seo.product.recommendedUse},{'@type':'PropertyValue',name:'Solubility',value:seo.product.solubility},{'@type':'PropertyValue',name:'Pack sizes',value:seo.product.sizes},{'@type':'PropertyValue',name:'Typical MOQ',value:seo.product.moq},{'@type':'PropertyValue',name:'Typical lead time',value:seo.product.leadTime}]};return {'@context':'https://schema.org','@type':'WebPage',name:seo.title,description:seo.description,url}}
