import { useEffect, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { Building2, CheckCircle2, Mail, Send } from 'lucide-react';
import wsClient from '../api/ws';

const initial=product=>({name:'',company:'',country:'United States',email:'',whatsapp:'',businessType:'formulator-manufacturer',salesChannels:'',websiteUrl:'',targetRetailPrice:'',annualVolume:'',productCategory:'active-ingredients',specifications:product,estimatedQuantity:'',deliveryDestination:'',targetDelivery:'',message:'',website:''});
export function QuoteForm({initialProduct='',compact=false}){
  const [form,setForm]=useState(()=>initial(initialProduct)); const [status,setStatus]=useState({sending:false,error:'',reference:''});
  useEffect(()=>{if(initialProduct)setForm(x=>({...x,specifications:initialProduct}))},[initialProduct]); const update=e=>setForm(x=>({...x,[e.target.name]:e.target.value}));
  const submit=async e=>{e.preventDefault();setStatus({sending:true,error:'',reference:''});try{const res=await fetch('/api/quotes/public',{method:'POST',headers:{'Content-Type':'application/json','X-Visitor-Id':wsClient.getVisitorId()},body:JSON.stringify(form)});const result=await res.json();if(!res.ok)throw new Error(result.message||'Unable to submit inquiry');setStatus({sending:false,error:'',reference:result.data.reference});setForm(initial(''))}catch(err){setStatus({sending:false,error:err.message,reference:''})}};
  if(status.reference)return <div className="rounded-3xl bg-[#eee4dc] p-8 text-center"><CheckCircle2 className="mx-auto text-[#8d4940]" size={44}/><h2 className="mt-4 font-heading text-2xl font-bold">Your ingredient inquiry is with us.</h2><p className="mt-2 text-[#695751]">Our technical sales team will follow up. Reference: <strong>{status.reference}</strong></p></div>;
  return <form onSubmit={submit} className={`grid gap-6 ${compact?'':'rounded-[2rem] bg-white p-6 shadow-sm sm:p-9'}`}>
    <input name="website" value={form.website} onChange={update} className="hidden" tabIndex="-1" autoComplete="off"/>
    <div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#a05247]">1 · Contact</p><div className="mt-4 grid gap-5 sm:grid-cols-2">{[['name','Your name *','text'],['company','Company *','text'],['email','Business email *','email'],['whatsapp','Phone / WhatsApp','text'],['websiteUrl','Company website','url'],['country','Country *','text']].map(([name,label,type])=><label key={name}><span className="mb-2 block text-sm font-semibold">{label}</span><input required={['name','company','email','country'].includes(name)} type={type} name={name} value={form[name]} onChange={update} className="w-full rounded-xl border-[#2d201d]/15"/></label>)}</div></div>
    <div className="border-t border-[#2d201d]/10 pt-6"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#a05247]">2 · Organization & demand</p><div className="mt-4 grid gap-5 sm:grid-cols-2">
      <label><span className="mb-2 block text-sm font-semibold">Organization type *</span><select required name="businessType" value={form.businessType} onChange={update} className="w-full rounded-xl border-[#2d201d]/15"><option value="formulator-manufacturer">Formulator / manufacturer</option><option value="beauty-brand">Beauty brand</option><option value="contract-manufacturer">Contract manufacturer</option><option value="laboratory">Laboratory / R&D studio</option><option value="distributor">Ingredient distributor</option></select></label>
      <label><span className="mb-2 block text-sm font-semibold">Target market(s) *</span><input required name="salesChannels" value={form.salesChannels} onChange={update} className="w-full rounded-xl border-[#2d201d]/15" placeholder="e.g. EU + United States"/></label>
      <label><span className="mb-2 block text-sm font-semibold">Target material cost</span><input name="targetRetailPrice" value={form.targetRetailPrice} onChange={update} className="w-full rounded-xl border-[#2d201d]/15" placeholder="e.g. USD/kg target"/></label>
      <label><span className="mb-2 block text-sm font-semibold">Estimated annual volume</span><input name="annualVolume" value={form.annualVolume} onChange={update} className="w-full rounded-xl border-[#2d201d]/15" placeholder="e.g. 500–1,000 kg"/></label>
    </div></div>
    <div className="border-t border-[#2d201d]/10 pt-6"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#a05247]">3 · Material requirement</p><div className="mt-4 grid gap-5 sm:grid-cols-2">
      <label><span className="mb-2 block text-sm font-semibold">Ingredient category</span><select name="productCategory" value={form.productCategory} onChange={update} className="w-full rounded-xl border-[#2d201d]/15"><option value="active-ingredients">Active ingredients</option><option value="botanical-extracts">Botanical extracts</option><option value="functional-materials">Functional materials</option><option value="documentation">Documentation request</option><option value="sample">Evaluation sample</option></select></label>
      <label><span className="mb-2 block text-sm font-semibold">Estimated first order (kg) *</span><input required type="number" min="1" name="estimatedQuantity" value={form.estimatedQuantity} onChange={update} className="w-full rounded-xl border-[#2d201d]/15" placeholder="e.g. 20"/></label>
    </div><label className="mt-5 block"><span className="mb-2 block text-sm font-semibold">Ingredient, INCI or formulation brief *</span><textarea name="specifications" required rows="4" value={form.specifications} onChange={update} className="w-full rounded-xl border-[#2d201d]/15" placeholder="Include dosage form, target function, use level, process or pH constraints."/></label><label className="mt-5 block"><span className="mb-2 block text-sm font-semibold">Required documents, delivery destination and timing</span><textarea name="message" rows="4" value={form.message} onChange={update} className="w-full rounded-xl border-[#2d201d]/15" placeholder="e.g. TDS, SDS, representative COA; Shanghai; needed for bench trial in October"/></label></div>
    {status.error&&<p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{status.error}</p>}<button disabled={status.sending} className="inline-flex items-center justify-center gap-2 rounded-full bg-[#2d201d] px-7 py-4 font-semibold text-white hover:bg-[#a05247] disabled:opacity-50"><Send size={18}/>{status.sending?'Sending…':'Send ingredient inquiry'}</button><label className="flex items-start gap-3 text-xs leading-5 text-[#695751]"><input type="checkbox" required className="mt-1 rounded"/><span>I am authorized to submit this B2B inquiry. I acknowledge the <Link to="/privacy" target="_blank">Privacy Policy</Link> and <Link to="/terms" target="_blank">Terms of Use</Link>.</span></label>
  </form>;
}
export default function Contact(){const [params]=useSearchParams();return <div className="min-h-screen bg-[#fbf7f2] pt-24"><section className="bg-[#2d201d] px-5 py-20 text-center text-white"><p className="text-xs font-bold uppercase tracking-[.24em] text-[#eeb8a8]">Samples · documents · commercial supply</p><h1 className="mt-4 font-heading text-5xl font-medium">Tell us what the formula needs.</h1><p className="mx-auto mt-5 max-w-2xl text-lg leading-8 text-white/65">Share the ingredient or functional brief, target market, evaluation quantity and required documents so we can respond with the relevant grade and supply path.</p></section><main className="mx-auto grid max-w-6xl gap-10 px-5 py-16 lg:grid-cols-[.65fr_1.35fr]"><aside><Building2 size={32} className="text-[#a05247]"/><h2 className="mt-5 font-heading text-2xl font-bold">A useful brief includes</h2><ul className="mt-4 space-y-3 text-sm leading-6 text-[#695751]">{['Ingredient name, INCI or target function','Dosage form and processing limits','Target market and compliance needs','Evaluation and annual volumes','Required TDS, SDS, COA or statements','Delivery destination and project timing'].map(x=><li key={x}>— {x}</li>)}</ul><a className="mt-7 flex items-center gap-2 font-semibold text-[#a05247]" href="mailto:hello@aureliabeauty.com"><Mail size={18}/>hello@aureliabeauty.com</a></aside><QuoteForm initialProduct={params.get('product')||''}/></main></div>}
