import { useMemo, useState } from 'react';
import { Search, SlidersHorizontal } from 'lucide-react';
import { useStore } from '../context/StoreContext';
import { categories } from '../data/products';
import ProductCard from '../components/ProductCard';

export default function Products(){
  const {state}=useStore(); const [category,setCategory]=useState('all'); const [query,setQuery]=useState('');
  const products=useMemo(()=>state.products.filter(p=>(category==='all'||p.category===category)&&`${p.name} ${p.description} ${p.wash||''}`.toLowerCase().includes(query.toLowerCase())),[state.products,category,query]);
  return <div className="min-h-screen bg-[#fbf7f2] pt-24"><section className="bg-[#eadbd2] px-5 py-20 text-center"><p className="text-xs font-bold uppercase tracking-[.26em] text-[#a05247]">Shop Aurelia</p><h1 className="mt-4 font-heading text-5xl font-medium text-[#2d201d] sm:text-6xl">The beauty wardrobe.</h1><p className="mx-auto mt-5 max-w-2xl text-lg leading-8 text-[#715f59]">High-performance essentials with elegant textures, modern color and a skin-first point of view.</p></section><main className="mx-auto max-w-7xl px-5 py-12 sm:px-8"><div className="flex flex-col gap-5 border-b border-[#2d201d]/10 pb-7 lg:flex-row lg:items-center lg:justify-between"><div className="flex flex-wrap gap-2">{categories.map(c=><button key={c.id} onClick={()=>setCategory(c.id)} className={`rounded-full px-5 py-2.5 text-sm font-semibold transition ${category===c.id?'bg-[#2d201d] text-white':'border border-[#2d201d]/15 bg-white text-[#594742] hover:border-[#a05247]'}`}>{c.name}</button>)}</div><label className="relative block min-w-[280px]"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-[#75635d]" size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search products or benefits" className="w-full rounded-full border-[#2d201d]/15 bg-white py-3 pl-11 pr-4"/></label></div><div className="my-8 flex items-center justify-between"><p className="text-sm text-[#75635d]">{products.length} beauty essentials</p><span className="flex items-center gap-2 text-sm font-semibold"><SlidersHorizontal size={16}/> Curated by ritual</span></div>{products.length?<div className="grid gap-x-6 gap-y-12 sm:grid-cols-2 lg:grid-cols-3">{products.map((p,i)=><ProductCard key={p.id} product={p} index={i}/>)}</div>:<div className="py-24 text-center"><h2 className="font-heading text-2xl font-medium">Nothing matched that search</h2><p className="mt-2 text-[#75635d]">Try another product, benefit or category.</p></div>}<section className="mt-20 rounded-[2rem] bg-[#2d201d] p-9 text-white sm:flex sm:items-center sm:justify-between"><div><h2 className="font-heading text-3xl font-medium">Not sure where to begin?</h2><p className="mt-2 text-white/60">Tell us what you want your ritual to feel like—we’ll help edit the options.</p></div><a href="/contact" className="mt-5 inline-block rounded-full bg-white px-6 py-3 font-semibold text-[#2d201d] sm:mt-0">Ask Aurelia</a></section></main></div>;
}
