import { useState } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { Menu, X, UserRound, Sparkles } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import { useStore } from '../context/StoreContext';

export default function Header(){
  const [open,setOpen]=useState(false); const location=useLocation(); const {user}=useAuth(); const {state}=useStore(); const editCount=state.rfqAssortment.reduce((sum,item)=>sum+item.quantity,0);
  const nav=[['/products','Products'],['/services/skin-ritual','Skin Ritual'],['/services/wholesale-private-label','Partners'],['/about','Our Story'],['/news-blog/','Journal'],['/faq','FAQ']];
  return <><div className="fixed inset-x-0 top-0 z-[60] bg-[#2d201d] py-2 text-center text-[10px] font-bold uppercase tracking-[.2em] text-white">Complimentary consultations · Vegan core formulas · Thoughtfully made</div><header className="fixed inset-x-0 top-8 z-50 border-b border-[#2d201d]/10 bg-[#fbf7f2]/92 backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-5 sm:px-8"><Link to="/" className="font-heading text-2xl font-medium tracking-[.08em] text-[#2d201d]">AURELIA <span className="text-[10px] font-bold tracking-[.22em] text-[#a05247]">BEAUTY</span></Link><nav className="hidden items-center gap-6 xl:flex">{nav.map(([path,label])=><Link key={path} to={path} className={`text-sm font-semibold ${location.pathname.startsWith(path)?'text-[#a05247]':'text-[#51413d] hover:text-[#a05247]'}`}>{label}</Link>)}</nav><div className="flex items-center gap-1"><Link to="/contact" className="hidden rounded-full bg-[#a05247] px-4 py-2.5 text-sm font-semibold text-white md:block">Partner with us</Link><Link to="/login" aria-label={user?'Account':'Sign in'} className="rounded-full p-2 hover:bg-black/5"><UserRound size={19}/></Link><Link to="/quote" aria-label="Partner sample edit" className="relative rounded-full p-2 hover:bg-black/5"><Sparkles size={19}/>{editCount>0&&<span className="absolute -right-1 -top-1 grid h-5 min-w-5 place-items-center rounded-full bg-[#a05247] px-1 text-[10px] font-bold text-white">{editCount}</span>}</Link><button onClick={()=>setOpen(!open)} className="rounded-full p-2 xl:hidden" aria-label="Menu">{open?<X/>:<Menu/>}</button></div></div>{open&&<nav className="border-t bg-[#fbf7f2] px-5 py-5 xl:hidden">{nav.map(([path,label])=><Link onClick={()=>setOpen(false)} className="block py-3 font-semibold" key={path} to={path}>{label}</Link>)}<Link onClick={()=>setOpen(false)} to="/contact" className="mt-3 block rounded-full bg-[#a05247] px-5 py-3 text-center font-semibold text-white">Partner with us</Link></nav>}</header></>;
}
